const core = @import("core.zig");
const development_matrix = @import("development_matrix.zig");
const shader_compiler = @import("shader/compiler.zig");
pub const ShaderReflection = @import("shader/reflection.zig");

const runtime = @import("runtime/window_context.zig");

pub const BackendPreference = core.BackendPreference;
pub const Backend = core.Backend;
pub const AdapterDeviceType = core.AdapterDeviceType;
pub const AdapterPowerPreference = core.AdapterPowerPreference;
pub const AdapterInfo = core.AdapterInfo;
pub const AdapterSelectionDescriptor = core.AdapterSelectionDescriptor;
pub const AdapterList = core.AdapterList;
pub const DeviceFeatures = core.DeviceFeatures;
pub const DeviceLimits = core.DeviceLimits;
pub const FormatCapabilities = core.FormatCapabilities;
pub const DeviceCapabilitySource = core.DeviceCapabilitySource;
pub const DeviceCapabilityReport = core.DeviceCapabilityReport;
pub const BackendAvailability = core.BackendAvailability;
pub const BackendSelectionOptions = core.BackendSelectionOptions;
pub const BackendSelectionError = core.BackendSelectionError;
pub const ErrorCategory = core.ErrorCategory;
pub const ObjectCacheError = core.ObjectCacheError;
pub const AdvancedFeatureError = core.AdvancedFeatureError;
pub const ObjectCacheMode = core.ObjectCacheMode;
pub const ObjectCachePolicy = core.ObjectCachePolicy;
pub const ObjectCacheKind = core.ObjectCacheKind;
pub const ObjectCacheStats = core.ObjectCacheStats;
pub const ObjectCacheDiagnostics = core.ObjectCacheDiagnostics;
pub const DriverCacheKind = core.DriverCacheKind;
pub const DriverCacheIdentityDescriptor = core.DriverCacheIdentityDescriptor;
pub const DriverPipelineCacheDescriptor = core.DriverPipelineCacheDescriptor;
pub const DriverPipelineCachePlan = core.DriverPipelineCachePlan;
pub const StabilityRunDescriptor = core.StabilityRunDescriptor;
pub const StabilityRunDiagnostics = core.StabilityRunDiagnostics;
pub const ResourceAccess = core.ResourceAccess;
pub const ResourceUsageKind = core.ResourceUsageKind;
pub const ResourceHazard = core.ResourceHazard;
pub const ResourceUsageTransition = core.ResourceUsageTransition;
pub const ResourceUsageState = core.ResourceUsageState;
pub const TransientResourceKind = core.TransientResourceKind;
pub const TransientResourceDescriptor = core.TransientResourceDescriptor;
pub const BufferBarrierDescriptor = core.BufferBarrierDescriptor;
pub const TextureBarrierDescriptor = core.TextureBarrierDescriptor;
pub const FenceKind = core.FenceKind;
pub const FenceDescriptor = core.FenceDescriptor;
pub const FenceSignalDescriptor = core.FenceSignalDescriptor;
pub const FenceWaitDescriptor = core.FenceWaitDescriptor;
pub const EventDescriptor = core.EventDescriptor;
pub const EventSignalDescriptor = core.EventSignalDescriptor;
pub const EventWaitDescriptor = core.EventWaitDescriptor;
pub const QueueKind = core.QueueKind;
pub const QueueCapabilities = core.QueueCapabilities;
pub const QueueDescriptor = core.QueueDescriptor;
pub const TransferBatchDescriptor = core.TransferBatchDescriptor;
pub const TransferBatchPlan = core.TransferBatchPlan;
pub const QueueOwnershipTransferDescriptor = core.QueueOwnershipTransferDescriptor;
pub const DebugGroupStack = core.DebugGroupStack;
pub const DebugSignpostDescriptor = core.DebugSignpostDescriptor;
pub const DebugLabelTarget = core.DebugLabelTarget;
pub const DebugLabelDescriptor = core.DebugLabelDescriptor;
pub const VulkanNativeHandles = core.VulkanNativeHandles;
pub const MetalNativeHandles = core.MetalNativeHandles;
pub const NativeHandles = core.NativeHandles;
pub const NativeHandleLifetime = core.NativeHandleLifetime;
pub const NativeHandleView = core.NativeHandleView;
pub const nativeHandleView = core.nativeHandleView;
pub const NativeCommandEncoderKind = core.NativeCommandEncoderKind;
pub const NativeCommandInsertionPoint = core.NativeCommandInsertionPoint;
pub const NativeCommandCallback = core.NativeCommandCallback;
pub const NativeCommandInsertionDescriptor = core.NativeCommandInsertionDescriptor;
pub const ContextOptions = core.ContextOptions;
pub const Context = core.Context;
pub const Adapter = core.Adapter;
pub const Extent2D = core.Extent2D;
pub const SurfaceProvider = core.SurfaceProvider;
pub const VulkanSurfaceProvider = core.VulkanSurfaceProvider;
pub const SurfaceSource = core.SurfaceSource;
pub const SurfaceDescriptor = core.SurfaceDescriptor;
pub const TextureFormat = core.TextureFormat;
pub const TextureFormatKind = core.TextureFormatKind;
pub const shader_reflection_schema_version = core.shader_reflection_schema_version;
pub const ShaderSourceLanguage = core.ShaderSourceLanguage;
pub const ShaderArtifact = core.ShaderArtifact;
pub const ShaderSource = core.ShaderSource;
pub const ShaderModuleDescriptor = core.ShaderModuleDescriptor;
pub const ShaderStage = core.ShaderStage;
pub const ShaderCompileProfile = core.ShaderCompileProfile;
pub const ShaderLibraryEntryDescriptor = core.ShaderLibraryEntryDescriptor;
pub const ShaderLibraryDescriptor = core.ShaderLibraryDescriptor;
pub const ShaderLibraryCacheKeyDescriptor = core.ShaderLibraryCacheKeyDescriptor;
pub const ShaderModuleCacheKeyDescriptor = core.ShaderModuleCacheKeyDescriptor;
pub const ShaderSpecializationValueKind = core.ShaderSpecializationValueKind;
pub const ShaderSpecializationValue = core.ShaderSpecializationValue;
pub const ShaderSpecializationConstant = core.ShaderSpecializationConstant;
pub const ShaderSpecializationDescriptor = core.ShaderSpecializationDescriptor;
pub const ShaderReflectionArtifact = core.ShaderReflectionArtifact;
pub const ShaderReflectionBinding = core.ShaderReflectionBinding;
pub const ShaderReflectionBindGroup = core.ShaderReflectionBindGroup;
pub const ShaderReflectionVertexInput = core.ShaderReflectionVertexInput;
pub const ShaderStageReflection = core.ShaderStageReflection;
pub const ShaderReflectionSource = core.ShaderReflectionSource;
pub const descriptorIndexingRangeCountForReflection = core.descriptorIndexingRangeCountForReflection;
pub const deriveDescriptorIndexingLayoutFromReflection = core.deriveDescriptorIndexingLayoutFromReflection;
pub const ProgrammableStageDescriptor = core.ProgrammableStageDescriptor;
pub const VertexFormat = core.VertexFormat;
pub const VertexStepFunction = core.VertexStepFunction;
pub const VertexAttributeDescriptor = core.VertexAttributeDescriptor;
pub const VertexBufferLayoutDescriptor = core.VertexBufferLayoutDescriptor;
pub const VertexDescriptor = core.VertexDescriptor;
pub const PrimitiveTopology = core.PrimitiveTopology;
pub const Winding = core.Winding;
pub const CullMode = core.CullMode;
pub const TriangleFillMode = core.TriangleFillMode;
pub const TessellationDomain = core.TessellationDomain;
pub const TessellationPartitionMode = core.TessellationPartitionMode;
pub const TessellationDescriptor = core.TessellationDescriptor;
pub const VulkanTessellationLowering = core.VulkanTessellationLowering;
pub const MetalTessellationLowering = core.MetalTessellationLowering;
pub const MeshPipelineDescriptor = core.MeshPipelineDescriptor;
pub const VulkanMeshPipelineLowering = core.VulkanMeshPipelineLowering;
pub const MetalMeshPipelineLowering = core.MetalMeshPipelineLowering;
pub const AccelerationStructureKind = core.AccelerationStructureKind;
pub const AccelerationStructureDescriptor = core.AccelerationStructureDescriptor;
pub const AccelerationStructureBuildSizes = core.AccelerationStructureBuildSizes;
pub const AccelerationStructureInstanceDescriptor = core.AccelerationStructureInstanceDescriptor;
pub const estimateAccelerationStructureBuildSizes = core.estimateAccelerationStructureBuildSizes;
pub const RayTracingShaderGroupKind = core.RayTracingShaderGroupKind;
pub const RayTracingShaderGroupDescriptor = core.RayTracingShaderGroupDescriptor;
pub const RayTracingPipelineDescriptor = core.RayTracingPipelineDescriptor;
pub const VulkanRayTracingPipelineLowering = core.VulkanRayTracingPipelineLowering;
pub const MetalIntersectionFunctionDescriptor = core.MetalIntersectionFunctionDescriptor;
pub const MetalRayTracingLowering = core.MetalRayTracingLowering;
pub const ShaderBindingTableDescriptor = core.ShaderBindingTableDescriptor;
pub const ShaderBindingTableLayout = core.ShaderBindingTableLayout;
pub const DepthBiasDescriptor = core.DepthBiasDescriptor;
pub const ColorWriteMask = core.ColorWriteMask;
pub const BlendFactor = core.BlendFactor;
pub const BlendOperation = core.BlendOperation;
pub const RenderPipelineBlendDescriptor = core.RenderPipelineBlendDescriptor;
pub const CompareFunction = core.CompareFunction;
pub const StencilOperation = core.StencilOperation;
pub const StencilFaceDescriptor = core.StencilFaceDescriptor;
pub const StencilDescriptor = core.StencilDescriptor;
pub const DepthStencilDescriptor = core.DepthStencilDescriptor;
pub const RenderPipelineColorAttachmentDescriptor = core.RenderPipelineColorAttachmentDescriptor;
pub const RenderPipelineDescriptor = core.RenderPipelineDescriptor;
pub const RenderPipelineCacheKeyDescriptor = core.RenderPipelineCacheKeyDescriptor;
pub const ComputePipelineDescriptor = core.ComputePipelineDescriptor;
pub const ComputePipelineCacheKeyDescriptor = core.ComputePipelineCacheKeyDescriptor;
pub const ShaderError = core.ShaderError;
pub const PipelineError = core.PipelineError;
pub const LoadAction = core.LoadAction;
pub const StoreAction = core.StoreAction;
pub const RenderPassAttachmentOptions = core.RenderPassAttachmentOptions;
pub const RenderPassColorAttachmentTarget = runtime.RenderPassColorAttachmentTarget;
pub const RenderPassColorAttachmentDescriptor = runtime.RenderPassColorAttachmentDescriptor;
pub const RenderPassDepthAttachmentTarget = runtime.RenderPassDepthAttachmentTarget;
pub const RenderPassDepthAttachmentDescriptor = runtime.RenderPassDepthAttachmentDescriptor;
pub const RenderPassStencilAttachmentTarget = runtime.RenderPassStencilAttachmentTarget;
pub const RenderPassStencilAttachmentDescriptor = runtime.RenderPassStencilAttachmentDescriptor;
pub const RenderPassDescriptor = runtime.RenderPassDescriptor;
pub const IndexType = core.IndexType;
pub const VertexBufferBinding = core.VertexBufferBinding;
pub const BindGroupBinding = core.BindGroupBinding;
pub const ResourceTableBinding = core.ResourceTableBinding;
pub const Viewport = core.Viewport;
pub const ScissorRect = core.ScissorRect;
pub const BlendColor = core.BlendColor;
pub const StencilReference = core.StencilReference;
pub const DrawPrimitivesDescriptor = core.DrawPrimitivesDescriptor;
pub const DrawIndexedPrimitivesDescriptor = core.DrawIndexedPrimitivesDescriptor;
pub const DrawPrimitivesIndirectDescriptor = core.DrawPrimitivesIndirectDescriptor;
pub const DrawIndexedPrimitivesIndirectDescriptor = core.DrawIndexedPrimitivesIndirectDescriptor;
pub const MultiDrawPrimitivesDescriptor = core.MultiDrawPrimitivesDescriptor;
pub const MultiDrawIndexedPrimitivesDescriptor = core.MultiDrawIndexedPrimitivesDescriptor;
pub const QueryType = core.QueryType;
pub const PipelineStatisticFlags = core.PipelineStatisticFlags;
pub const QuerySetDescriptor = core.QuerySetDescriptor;
pub const ProfilerMarkerDescriptor = core.ProfilerMarkerDescriptor;
pub const QueryResolveDescriptor = core.QueryResolveDescriptor;
pub const QueryReadbackDescriptor = core.QueryReadbackDescriptor;
pub const QueryError = core.QueryError;
pub const DispatchThreadgroupsDescriptor = core.DispatchThreadgroupsDescriptor;
pub const DispatchThreadsDescriptor = core.DispatchThreadsDescriptor;
pub const DispatchThreadgroupsIndirectDescriptor = core.DispatchThreadgroupsIndirectDescriptor;
pub const ComputeAtomicOperations = core.ComputeAtomicOperations;
pub const ComputeAtomicDescriptor = core.ComputeAtomicDescriptor;
pub const ThreadgroupMemoryDescriptor = core.ThreadgroupMemoryDescriptor;
pub const CommandBufferDescriptor = core.CommandBufferDescriptor;
pub const CopyBufferToBufferDescriptor = core.CopyBufferToBufferDescriptor;
pub const FillBufferDescriptor = core.FillBufferDescriptor;
pub const BufferTextureCopyLayout = core.BufferTextureCopyLayout;
pub const CopyBufferToTextureDescriptor = core.CopyBufferToTextureDescriptor;
pub const CopyTextureToBufferDescriptor = core.CopyTextureToBufferDescriptor;
pub const CopyTextureToTextureDescriptor = core.CopyTextureToTextureDescriptor;
pub const ResolvedBufferTextureCopy = core.ResolvedBufferTextureCopy;
pub const ResolvedTextureTextureCopy = core.ResolvedTextureTextureCopy;
pub const CommandBufferState = core.CommandBufferState;
pub const RenderCommandEncoderState = core.RenderCommandEncoderState;
pub const BlitCommandEncoderState = core.BlitCommandEncoderState;
pub const ComputeCommandEncoderState = core.ComputeCommandEncoderState;
pub const CommandBufferDebugState = core.CommandBufferDebugState;
pub const RenderCommandEncoderDebugState = core.RenderCommandEncoderDebugState;
pub const BlitCommandEncoderDebugState = core.BlitCommandEncoderDebugState;
pub const ComputeCommandEncoderDebugState = core.ComputeCommandEncoderDebugState;
pub const CommandEncodingError = core.CommandEncodingError;
pub const TextureDimension = core.TextureDimension;
pub const TextureShape = core.TextureShape;
pub const TextureViewDimension = core.TextureViewDimension;
pub const TextureUsage = core.TextureUsage;
pub const TextureDescriptor = core.TextureDescriptor;
pub const ExternalHandleKind = core.ExternalHandleKind;
pub const ExternalResourceOwnership = core.ExternalResourceOwnership;
pub const ExternalHandleDescriptor = core.ExternalHandleDescriptor;
pub const ExternalMemoryDescriptor = core.ExternalMemoryDescriptor;
pub const ExternalBufferDescriptor = core.ExternalBufferDescriptor;
pub const ExternalTextureDescriptor = core.ExternalTextureDescriptor;
pub const ExternalSemaphoreDescriptor = core.ExternalSemaphoreDescriptor;
pub const ExternalEventDescriptor = core.ExternalEventDescriptor;
pub const TextureViewDescriptor = core.TextureViewDescriptor;
pub const ResolvedTextureViewDescriptor = core.ResolvedTextureViewDescriptor;
pub const Origin3D = core.Origin3D;
pub const Size3D = core.Size3D;
pub const Region3D = core.Region3D;
pub const TextureRegion = core.TextureRegion;
pub const SparseResidency = core.SparseResidency;
pub const SparseBufferDescriptor = core.SparseBufferDescriptor;
pub const SparseBufferMappingDescriptor = core.SparseBufferMappingDescriptor;
pub const SparseTextureKind = core.SparseTextureKind;
pub const SparseTextureDescriptor = core.SparseTextureDescriptor;
pub const SparseMipTailDescriptor = core.SparseMipTailDescriptor;
pub const SparseTextureMappingDescriptor = core.SparseTextureMappingDescriptor;
pub const SparseMappingCommitDescriptor = core.SparseMappingCommitDescriptor;
pub const SparseResidencyDiagnostics = core.SparseResidencyDiagnostics;
pub const SparseResidencyMap = core.SparseResidencyMap;
pub const TextureReplaceRegionDescriptor = core.TextureReplaceRegionDescriptor;
pub const ResolvedTextureReplaceRegion = core.ResolvedTextureReplaceRegion;
pub const TextureUpload2DDescriptor = core.TextureUpload2DDescriptor;
pub const GenerateMipmapsDescriptor = core.GenerateMipmapsDescriptor;
pub const ResolvedGenerateMipmapsDescriptor = core.ResolvedGenerateMipmapsDescriptor;
pub const TextureError = core.TextureError;
pub const SamplerMinMagFilter = core.SamplerMinMagFilter;
pub const SamplerMipFilter = core.SamplerMipFilter;
pub const SamplerAddressMode = core.SamplerAddressMode;
pub const SamplerBorderColor = core.SamplerBorderColor;
pub const SamplerDescriptor = core.SamplerDescriptor;
pub const SamplerCacheKeyDescriptor = core.SamplerCacheKeyDescriptor;
pub const SamplerError = core.SamplerError;
pub const HeapStorageMode = core.HeapStorageMode;
pub const HeapDescriptor = core.HeapDescriptor;
pub const HeapError = core.HeapError;
pub const ShaderVisibility = core.ShaderVisibility;
pub const BindingLocation = core.BindingLocation;
pub const BindingResourceKind = core.BindingResourceKind;
pub const StorageAccess = core.StorageAccess;
pub const BindGroupLayoutEntry = core.BindGroupLayoutEntry;
pub const BindGroupLayoutDescriptor = core.BindGroupLayoutDescriptor;
pub const AdvancedBindingModel = core.AdvancedBindingModel;
pub const DescriptorIndexingRange = core.DescriptorIndexingRange;
pub const DescriptorIndexingLayoutDescriptor = core.DescriptorIndexingLayoutDescriptor;
pub const ResourceTableSlot = core.ResourceTableSlot;
pub const BindGroupLayoutCacheKeyDescriptor = core.BindGroupLayoutCacheKeyDescriptor;
pub const PipelineLayoutCacheKeyDescriptor = core.PipelineLayoutCacheKeyDescriptor;
pub const BufferBindingDescriptor = core.BufferBindingDescriptor;
pub const TextureViewBindingDescriptor = core.TextureViewBindingDescriptor;
pub const SamplerBindingDescriptor = core.SamplerBindingDescriptor;
pub const StaticSamplerDescriptor = core.StaticSamplerDescriptor;
pub const BindGroupResourceDescriptor = core.BindGroupResource;
pub const BindGroupEntryDescriptor = core.BindGroupEntry;
pub const BindGroupDescriptorShape = core.BindGroupDescriptor;
pub const BindGroupShapeResource = BindGroupResourceDescriptor;
pub const BindGroupShapeEntry = BindGroupEntryDescriptor;
pub const BindGroupShapeDescriptor = core.BindGroupDescriptor;
pub const DynamicOffset = core.DynamicOffset;
pub const DynamicOffsetList = core.DynamicOffsetList;
pub const SmallConstantDescriptor = core.SmallConstantDescriptor;
pub const SmallConstantError = core.SmallConstantError;
pub const RootConstantRange = core.RootConstantRange;
pub const RootConstantLayoutDescriptor = core.RootConstantLayoutDescriptor;
pub const RootConstantWriteDescriptor = core.RootConstantWriteDescriptor;
pub const RootConstantError = core.RootConstantError;
pub const BindingError = core.BindingError;
pub const PresentMode = core.PresentMode;
pub const SurfaceResizePolicy = core.SurfaceResizePolicy;
pub const SurfaceState = core.SurfaceState;
pub const PresentationDescriptor = core.PresentationDescriptor;
pub const PresentModeSupport = core.PresentModeSupport;
pub const PresentationResourceState = core.PresentationResourceState;
pub const SurfaceError = core.SurfaceError;
pub const SurfaceHandle = core.SurfaceHandle;
pub const SurfaceInfo = core.SurfaceInfo;
pub const SurfaceCollection = core.SurfaceCollection;
pub const ClearColorLike = core.ClearColorLike;
pub const BufferUsage = core.BufferUsage;
pub const ResourceStorageMode = core.ResourceStorageMode;
pub const BufferDescriptor = core.BufferDescriptor;
pub const BufferWriteDescriptor = core.BufferWriteDescriptor;
pub const BufferReadDescriptor = core.BufferReadDescriptor;
pub const BufferMapMode = core.BufferMapMode;
pub const BufferMapDescriptor = core.BufferMapDescriptor;
pub const BufferError = core.BufferError;
pub const selectBackend = core.selectBackend;
pub const enumerateAdapters = core.enumerateAdapters;
pub const classifyError = core.classifyError;
pub const textureFormatBytesPerPixel = core.textureFormatBytesPerPixel;
pub const textureFormatKind = core.textureFormatKind;
pub const isColorFormat = core.isColorFormat;
pub const isDepthFormat = core.isDepthFormat;
pub const isStencilFormat = core.isStencilFormat;
pub const isDepthStencilFormat = core.isDepthStencilFormat;
pub const isCompressedFormat = core.isCompressedFormat;
pub const isSrgbFormat = core.isSrgbFormat;
pub const mipDimension = core.mipDimension;
pub const maxMipLevelCountForExtent = core.maxMipLevelCountForExtent;

pub const WindowContext = runtime.WindowContext;
pub const WindowContextOptions = runtime.WindowContextOptions;
pub const ShaderCompilerOptions = shader_compiler.CompilerOptions;
pub const RenderShaderCompileOptions = shader_compiler.RenderShaderOptions;
pub const ComputeShaderCompileOptions = shader_compiler.ComputeShaderOptions;
pub const RenderShaderStages = shader_compiler.RenderShaderStages;
pub const CompiledRenderShader = shader_compiler.CompiledRenderShader;
pub const CompiledComputeShader = shader_compiler.CompiledComputeShader;
pub const ClearColor = runtime.ClearColor;
pub const Buffer = runtime.Buffer;
pub const MappedBufferRange = runtime.MappedBufferRange;
pub const Texture = runtime.Texture;
pub const ExternalTexture = runtime.ExternalTexture;
pub const TextureView = runtime.TextureView;
pub const SamplerState = runtime.SamplerState;
pub const ShaderModule = runtime.ShaderModule;
pub const RenderPipelineState = runtime.RenderPipelineState;
pub const ComputePipelineState = runtime.ComputePipelineState;
pub const BindGroupLayout = runtime.BindGroupLayout;
pub const AdvancedBindGroupLayout = runtime.AdvancedBindGroupLayout;
pub const BindGroupBufferBinding = runtime.BindGroupBufferBinding;
pub const BindGroupResource = runtime.BindGroupResource;
pub const BindGroupEntry = runtime.BindGroupEntry;
pub const BindGroupDescriptor = runtime.BindGroupDescriptor;
pub const BindGroup = runtime.BindGroup;
pub const ResourceTableDescriptor = runtime.ResourceTableDescriptor;
pub const ResourceTableUpdateDescriptor = runtime.ResourceTableUpdateDescriptor;
pub const ResourceTable = runtime.ResourceTable;
pub const CommandBuffer = runtime.CommandBuffer;
pub const BlitCommandEncoder = runtime.BlitCommandEncoder;
pub const RenderCommandEncoder = runtime.RenderCommandEncoder;
pub const ComputeCommandEncoder = runtime.ComputeCommandEncoder;
pub const RuntimeError = runtime.RuntimeError;
pub const Device = runtime.Device;
pub const Queue = runtime.Queue;
pub const Surface = runtime.Surface;
pub const Swapchain = runtime.Swapchain;

test {
    _ = development_matrix;
}

test "resource tracker records retain and release counts" {
    var tracker = runtime.ResourceTracker{};

    try @import("std").testing.expect(!tracker.hasLeaks());

    tracker.retain(.texture);
    tracker.retain(.texture_view);
    tracker.retain(.sampler_state);
    tracker.retain(.shader_module);
    tracker.retain(.render_pipeline_state);
    tracker.retain(.compute_pipeline_state);
    tracker.retain(.bind_group_layout);
    tracker.retain(.bind_group);
    try @import("std").testing.expect(tracker.hasLeaks());

    tracker.release(.bind_group);
    tracker.release(.bind_group_layout);
    tracker.release(.compute_pipeline_state);
    tracker.release(.texture_view);
    tracker.release(.sampler_state);
    tracker.release(.shader_module);
    tracker.release(.render_pipeline_state);
    tracker.release(.texture);
    try @import("std").testing.expect(!tracker.hasLeaks());
}

test "runtime command wrappers expose Metal-style ordering" {
    var command_buffer = runtime.CommandBuffer{ .backend = .metal };
    const color_attachments = [_]runtime.RenderPassColorAttachmentDescriptor{.{}};

    var encoder = try command_buffer.makeRenderCommandEncoder(.{
        .color_attachments = color_attachments[0..],
    });
    try encoder.endEncoding();
    try command_buffer.presentDrawable();
    try command_buffer.commit();

    try @import("std").testing.expect(!command_buffer.alive);
}

test "runtime command buffer exposes lifecycle status" {
    var command_buffer = runtime.CommandBuffer{
        .backend = .metal,
        .label_value = "frame",
    };

    try @import("std").testing.expectEqual(core.CommandBufferState.ready, command_buffer.state());
    try @import("std").testing.expectEqualStrings("frame", command_buffer.label().?);
    try command_buffer.commit();
    try @import("std").testing.expectEqual(core.CommandBufferState.committed, command_buffer.state());
}
